### PR TITLE
Support PHP 7.2

### PR DESCRIPTION
**Pull request by amcsi**
Starting with a `.travis.yml` file change to see what doesn't work.

### CODE REVIEW

**Comment by amcsi** [comment]
@weierophinney There are failures (only for _lowest_ dependencies) because of a deprecation in zend-validator:

```
1) ZendTest\Uri\MailtoTest::testInvalidMailtoUris with data set #2 ('mailto:foo@example.com/bar/baz')
idn_to_utf8(): INTL_IDNA_VARIANT_2003 is deprecated
/home/travis/build/zendframework/zend-uri/vendor/zendframework/zend-validator/src/EmailAddress.php:545
/home/travis/build/zendframework/zend-uri/vendor/zendframework/zend-validator/src/EmailAddress.php:494
/home/travis/build/zendframework/zend-uri/src/Mailto.php:54
/home/travis/build/zendframework/zend-uri/test/MailtoTest.php:157
```

Are deprecation warnings acceptable for lowest dependencies?
Otherwise probably the minimal dependency that introduces the fix to this deprecation (if intl is loaded) is in zend-validator 2.10.2: https://github.com/zendframework/zend-validator/commit/010084ddbd33299bf51ea6f0e07f8f4e8bd832a8

**Comment by weierophinney** [comment]
In this case, bump the minimum supported version of zend-validator as part of the patch; that's essentially what is necessary to make this component work under 7.2. 

Thanks!

**Comment by amcsi** [comment]
@weierophinney I tried 2.10.1 which is one version lower than I anticipated, and it passes there for lowest.
I'm going to investigate to see which is truly the earliest good version.

By the way this tests pass for the current lowest (2.5.0) if the intl extension is not loaded. Apparently the iffy behavior actually starts happening once the intl extension is enabled.

**Comment by amcsi** [comment]
Seems like `^2.10` is enough. #175, https://github.com/zendframework/zend-validator/releases/tag/release-2.10.0

**Comment by amcsi** [comment]
I've generated the `composer.lock` file by removing `vendor` and `composer.lock` and doing `composer install --ignore-platform-reqs`

**Comment by weierophinney** [comment]
Thanks, @amcsi !

**Pull request closed without merging**
