### PR TITLE
Fixes #13 : reserved characters in path should be unencoded

### LINKED ISSUE #13: Usage of reserved characters in path, unencoded
This issue was originally submitted as https://github.com/zendframework/zendframework/issues/6153.

This is a valid LinkedIn API URL:

```
https://api.linkedin.com/v1/people/~:(first-name,last-name,email-address)
```

Using the following code:

``` php
$uri = new \Zend\Uri\Http();
$uri->setScheme('https');
$uri->setHost('api.linkedin.com');
$uri->setPath('/v1/people/~:(first-name,last-name,email-address,picture-url)');
echo $uri;
```

Results in:

```
https://api.linkedin.com/v1/people/~:%28first-name,last-name,email-address,picture-url%29
```

The reserved bracket characters are escaped. This resulting URL is not a valid LinkedIn API URL.

Zend\Uri\Uri::toString() uses self::encodePath($this->path) internally, making it impossible to override encodePath()'s behaviour by extending Zend\Uri\Http and replacing the method.

My understanding of the RFC is that reserved characters need not necessarily be escaped where they are being used as delimiters. Should there be some way to represent URLs such as the above?

### PR DESCRIPTION
**Pull request by samsonasik**
Fixes #13

### CODE REVIEW

**Comment by samsonasik** [comment]
if the "un" prefix usage in the pr/tests for "unencoded" or "unreserved"  words are not grammatically correct, please let me know so I can change them.

**Comment by samsonasik** [comment]
Is there anything I can do to get it merged? Thank you.

**Comment by samsonasik** [comment]
is there any chance to get it merged? Thank you

**Comment by weierophinney** [comment]
Thanks, @samsonasik!

**Pull request merged**
